### ISSUE TITLE
PTX JIT compiler library not found

### ISSUE THREAD

**Issue by wonghang** [Theano/libgpuarray#555]
Hi,

I am installing libgpuarray v0.7.4 from the github. When I import theano, I got the following errors:
I am using the version of:

(1) Theano from github (rel-1.0.0rc1),
(2) CUDA 9.0 
(I am sure CUDA / cusolver works, I installed pycuda, scikit-cuda and could run them successfully)
(3) cuDNN 7.0.3
(4) nvidia driver 384.90

```
Python 3.5.2 (default, Sep 14 2017, 22:51:06) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano
Using cuDNN version 7003 on context None
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/Theano-1.0.0rc1-py3.5.egg/theano/gpuarray/__init__.py", line 220, in <module>
    use(config.device)
  File "/usr/local/lib/python3.5/dist-packages/Theano-1.0.0rc1-py3.5.egg/theano/gpuarray/__init__.py", line 207, in use
    init_dev(device, preallocate=preallocate)
  File "/usr/local/lib/python3.5/dist-packages/Theano-1.0.0rc1-py3.5.egg/theano/gpuarray/__init__.py", line 152, in init_dev
    pygpu.blas.gemm(0, tmp, tmp, 0, tmp, overwrite_c=True)
  File "pygpu/blas.pyx", line 149, in pygpu.blas.gemm
  File "pygpu/blas.pyx", line 47, in pygpu.blas.pygpu_blas_rgemm
pygpu.gpuarray.GpuArrayException: (b'cuLinkCreate: CUDA_ERROR_JIT_COMPILER_NOT_FOUND: PTX JIT compiler library not found', 3)

```

How to resolve it?

**Comment by abergeron** [comment]
This is because cuda doesn't find one of the library it installs.  Can you try reinstalling cuda?

**Comment by wonghang** [comment]
hi, the problem has been resolved by a guy on stackoverflow: https://stackoverflow.com/questions/47258882/theano-gpu-support-ptx-jit-compiler-library-not-found

**Comment by nouiz** [comment]
thanks for the update. I added a comment there.
